version: '3.9'
services:
  trial-api:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./api-level2
    volumes:
    - /app/node_modules
    - ./api-level2:/app
    ports:
      - '3000:3000'
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - '80:80'
